ALTER TABLE `scanRun` ADD COLUMN `expectedTasks` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `scanRun` ADD COLUMN `completedTasks` INTEGER NOT NULL DEFAULT 0;
ALTER TABLE `scanRun` ADD COLUMN `failedTasks` INTEGER NOT NULL DEFAULT 0;
